config:
 mirror_directory: /srv/mirrors
distributions:
 ubuntu:
   defaults:
     sections: main,restricted
     arch: amd64
     host: archive.ubuntu.com
     rootdir: ubuntu
     stable: true
     method: http
   releases: 
    oneiric:
     sections: main,restricted,universe,multiverse
     arch: amd64,i386
     host: archive.ubuntu.com
     rootdir: ubuntu
     stable: true
     method: http
     mirror_directory: /srv/archive/oneiric
    precise:
     sections: main, restricted,universe,multiverse
     arch: amd64,i386
     host: archive.ubuntu.com
     rootdir: ubuntu
     stable: false
     method: http
     mirror_directory: /srv/archive/precise
 debian:
   defaults:
    sections: main, contrib
    arch: amd64
    host: ftp.de.debian.org
    rootdir: debian
    stable: true
    method: http
   releases:
    squeeze:
     sections: main, contrib, non-free
     arch: amd64,i386
     host: ftp.de.debian.org
     rootdir: debian
     stable: true
     method: http
    sid:
     arch: amd64
     host: ftp.de.debian.org
     rootdir: debian
     stable: false
     method: http
