config:
 basefiles_directory: /srv/fai/config/basefiles/
suites:
 lucid:
  type: debian
  debootstrap_mirror_url: http://archive.ubuntu.com/ubuntu
  arch:
   i386:
    classname: 50_OS_UBUNTU_1004_i386
   amd64:
    classname: 50_OS_UBUNTU_1004_amd64
 squeeze:
  type: debian
  debootstrap_mirror_url: http://ftp.de.debian.org/debian
  arch:
   i386:
    classname: 50_OS_DEBIAN_6_i386
   amd64:
    classname: 50_OS_DEBIAN_6_amd64

